/**
 * NewsFeed Demo: Export Generators
 * Generate Markdown, HTML, and PDF (stub) exports
 */

import type { NewsStory, SelectionRationale } from "./why_picked.js";

export interface ExportResults {
  markdown: string;
  html: string;
  pdf: string;
}

/**
 * Generate Markdown export
 */
export function generateMarkdown(story: NewsStory, rationale: SelectionRationale): string {
  return `# ${story.title}

${rationale.fullRationale}

---

## Summary

${story.summary}

## Full Article

${story.body}

---

*Generated by PipelinePilot NewsFeed Demo*
*Story ID: ${story.id}*
`;
}

/**
 * Generate HTML export
 */
export function generateHTML(story: NewsStory, rationale: SelectionRationale): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${story.title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      line-height: 1.6;
      color: #333;
    }
    h1 {
      color: #2c3e50;
      border-bottom: 3px solid #3498db;
      padding-bottom: 10px;
    }
    .rationale {
      background: #f8f9fa;
      border-left: 4px solid #3498db;
      padding: 15px;
      margin: 20px 0;
    }
    .category {
      font-weight: bold;
      color: #e74c3c;
      font-size: 1.2em;
    }
    .metrics {
      font-family: monospace;
      background: #ecf0f1;
      padding: 10px;
      border-radius: 4px;
      margin: 10px 0;
    }
    .summary {
      font-size: 1.1em;
      font-style: italic;
      color: #555;
      margin: 20px 0;
    }
    .body {
      text-align: justify;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      font-size: 0.9em;
      color: #777;
    }
  </style>
</head>
<body>
  <h1>${story.title}</h1>

  <div class="rationale">
    <div class="category">${rationale.category}</div>
    <div class="metrics">${rationale.metricsLine}</div>
    <p><strong>Why This Article Matters:</strong></p>
    <p>${rationale.reason}</p>
    <p><strong>Source:</strong> <a href="${story.source.url}">${story.source.name}</a></p>
  </div>

  <h2>Summary</h2>
  <div class="summary">${story.summary}</div>

  <h2>Full Article</h2>
  <div class="body">${story.body.split('\n\n').map(p => `<p>${p}</p>`).join('\n')}</div>

  <div class="footer">
    <p><em>Generated by PipelinePilot NewsFeed Demo</em></p>
    <p>Story ID: ${story.id}</p>
  </div>
</body>
</html>
`;
}

/**
 * Generate PDF export (stub - returns message)
 */
export function generatePDF(story: NewsStory, rationale: SelectionRationale): string {
  return "PDF generation disabled in Phase 1 demo. Use Markdown or HTML exports, then convert with: wkhtmltopdf, pandoc, or browser print-to-PDF.";
}

/**
 * Generate all exports
 */
export function generateAllExports(story: NewsStory, rationale: SelectionRationale): ExportResults {
  return {
    markdown: generateMarkdown(story, rationale),
    html: generateHTML(story, rationale),
    pdf: generatePDF(story, rationale)
  };
}

export default generateAllExports;
